### ISSUE TITLE
Incorrect Target Account Result Returned When Executing hedera_signAndExecuteQuery on https://wc.hgraph.app/

### ISSUE THREAD

**Issue by soharang** [hashgraph/hedera-wallet-connect#119] opened 2024-04-22 07:43 UTC
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

1. Go to 'https://wc.hgraph.app/'
2. Input necessary field and process "Initialize WalletConnect" for both "dApp" and "Wallet" on the page.
3. Connet dApp to Wallet
4. Input necessary field as following and proceed "4. hedera_signAndExecuteQuery".
   - Account ID: 0.0.398606 
   - Payment account id: the account connected to dApp from the wallet as a signer.
5. Proceed request and check the query result.

**Expected behavior** A clear and concise description of what you expected to happen.
The account for the result from the query should be the account Id in the field named "Account ID", in this case, 0.0.398606.

**Screenshots** If applicable, add screenshots to help explain your problem.
The account for the result from the query is the payment account Id in the field named "Payment account id", in this case.
![image](https://github.com/hashgraph/hedera-wallet-connect/assets/32191478/fadb57f1-669d-4fa8-aaa5-887d4f3f84cd)

**Desktop (please complete the following information):**

**Additional context** Add any other context about the problem here.

**Comment by kantorcodes** [comment] 2024-11-04 16:01
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to 'https://wc.hgraph.app/'
> 2. Input necessary field and process "Initialize WalletConnect" for both "dApp" and "Wallet" on the page.
> 3. Connet dApp to Wallet
> 4. Input necessary field as following and proceed "4. hedera_signAndExecuteQuery".
>    
>    * Account ID: 0.0.398606
>    * Payment account id: the account connected to dApp from the wallet as a signer.
> 5. Proceed request and check the query result.
> 
> **Expected behavior** A clear and concise description of what you expected to happen. The account for the result from the query should be the account Id in the field named "Account ID", in this case, 0.0.398606.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem. The account for the result from the query is the payment account Id in the field named "Payment account id", in this case. ![image](https://private-user-images.githubusercontent.com/32191478/324369854-fadb57f1-669d-4fa8-aaa5-887d4f3f84cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MzYyNDQsIm5iZiI6MTczMDczNTk0NCwicGF0aCI6Ii8zMjE5MTQ3OC8zMjQzNjk4NTQtZmFkYjU3ZjEtNjY5ZC00ZmE4LWFhYTUtODg3ZDRmM2Y4NGNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDE1NTkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExYTA4N2Y3ZjJkNjNmNDFlNTBjZTNmY2IzYjg0ZjdjYzkxNjI2YjZkNTNkZmU1ZjJhZDYxNmFkZTFmZTExNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BOSmty8RDt6fqb0i2EuRZVjUDlCSgzZtChduaB05zyI)
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Additional context** Add any other context about the problem here.

Thanks for flagging this issue. I believe the issue is that the latest signer in the array was being pulled instead of what was provided in the `params`. The PR we are currently testing should resolve this.

**Comment by kantorcodes** [comment] 2024-11-13 17:52
I am closing this issue out as the newest canary release resolves this issue and can be tested on the docs: https://hwc-docs.hgraph.app/demos

**Closed by kantorcodes** 2024-11-13 17:52 UTC
Labels: Bug, P1
