### ISSUE TITLE
Issue with hedera-wallet-connect and transaction/query signature & execution with blade mobile

### ISSUE THREAD

**Issue by marelh02** [hashgraph/hedera-wallet-connect#64] opened 2024-02-19 15:26 UTC
**The bug**
Hello, I caught another problem, I managed to connect my demo dapp with blade wallet through QR code scan, then I sent a simple query to be signed and executed (hedera_signAndExecuteQuery), but I get the following error: {type: 'locked', message: "The user's wallet is locked.", code: 423, isError: true, source: '02'}, the same happens for transactions.

**To Reproduce the error** 
- Link the demo dapp to blade wallet
- Send a query or a transaction to be signed and executed
- catch the locked wallet error

**Expected behavior**
What I expected is to be prompted on my mobile to sign or reject the query/tx then see some output on my browser

**Screenshots** 
The locked wallet error
![image](https://github.com/hashgraph/hedera-wallet-connect/assets/97633566/2ffbfcbb-2e53-4c17-9a8e-a3f9dcdc2ab9)

The demo dapp succefully connected to blade
![image](https://github.com/hashgraph/hedera-wallet-connect/assets/97633566/6e658197-741c-465e-8d3e-7abaf3da4492)

**Desktop:**

- OS: Windows 11
- Browser: chrome, brave
- Version: latest

**Smartphone:**

- Device: Realme C55, iPhone 13
- OS: Android 13, iOS
- Wallet: Blade mobile

**Additional context**
I suspected there was something wrong with my code, but whenever I mess something up, I get an error telling me exactly what's wrong with the query/tx, so I suppose I'll trust the test code for now.
I'd like to mention my wallet is not locked at all, I can make transactions from it normally, when I am not opening blade, the hedera_signAndExecuteQuery promise stays pending with no errors, once I open blade it fails and I get that error. I tried it from my friends wallets, same behaviour.
and here is what I tried to sign and execute:

// 4. SignAndExecuteQuery
  export async function hedera_signAndExecuteQuery(dAppConnector: DAppConnector,accountId:string) {
    const query = new AccountInfoQuery().setAccountId(accountId)
    const params: SignAndExecuteQueryParams = {
      signerAccountId: 'hedera:testnet:' + accountId,
      // @ts-ignore
      query: queryToBase64String(query),
    }
    console.log("just before sending query");
    // @ts-ignore
    const { response } = await dAppConnector!.signAndExecuteQuery(params)
    const bytes = Buffer.from(response, 'base64')
    const accountInfo = AccountInfo.fromBytes(bytes)
    console.log(accountInfo)
    return accountInfo
  }
  
  
  // 5. hedera_signAndExecuteTransaction
  export async function hedera_signAndExecuteTransaction(dAppConnector: DAppConnector,sender:string,receiver:string) {
    const transaction = new TransferTransaction()
    .setTransactionId(TransactionId.generate(sender))
      .addHbarTransfer(sender, new Hbar(-1))
      .addHbarTransfer(receiver, new Hbar(+1))
  
    const params: SignAndExecuteTransactionParams = {
      // @ts-ignore
      transactionList: transactionToBase64String(transaction),
      signerAccountId: 'hedera:testnet:' + sender,
    }
  
    console.log(params)
  
    return await dAppConnector!.signAndExecuteTransaction(params)
  }

**Comment by hgraphql** [comment] 2024-02-20 14:21
@valeraOlexienko

Do you have any additional insight that might help debug this error?

**Comment by marelh02** [comment] 2024-03-07 14:49
Hello, I have an update for you: I used the hedera-wallet-connect library to create the logic that a wallet would have, I managed to link my test DApp with my test wallet, and when I try to sign and execute queries / transactions, I get prompted on the wallet side to accept (Window: confirm() method), if there is nothing wrong with my query/tx, it gets executed and I get some return on the Dapp side.

**Comment by marelh02** [comment] 2024-04-30 13:55
Hello. I have no more updates on this issue, still I would be interested to hear about its resolution. Thank you.

**Comment by hgraphql** [comment] 2024-05-16 14:53
hi @marelh02 Our team has tried to reproduce this, though we are not able to (it's possible something has been fixed since the original post. Here is the team members response. Does this problem persist for you or is it working as well?

On the latest version of hedera-wallet-connect (1.0.6), the bug does not reproduce, the hedera_signAndExecuteQuery and hedera_signAndExecuteTransaction functions provided by the author of the issue work correctly, i.e. transactions and query are executed successfully. At the same time, Blade Wallet works correctly, opening a modal window with confirmation of the transactions being sent. I assume that the problem was on the side of the Blade Wallet.

The results of the tested functions:

signAndExecuteTransaction:

{"nodeId":"0.0.3","transactionHash":"2771e9312d3b8086cbf92d6253ff39515f2861413a305937c974443d6416cb99c936223c73488f15a963e18c56567e12","transactionId":"0.0.4340749@1715614384.416549914"}

signAndExecuteQuery:

{"balance":"69.99483326 ℏ","accountId":"0.0.4340749","contractAccountId":"6ba87e79abb885e7b40cae77c3eeab3a2c473fb4","isDeleted":false,"proxyAccountId":null,"proxyReceived":"0 tℏ","key":"302d300706052b8104000a032200034751819da41437641c626f2743d63b9156894ad33027231a31b4fa99fd9deb16","sendRecordThreshold":"0 tℏ","receiveRecordThreshold":"0 tℏ","isReceiverSignatureRequired":false,"expirationTime":"1723215996.000000000","autoRenewPeriod":"[object Object]","accountMemo":"","ownedNfts":"0","maxAutomaticTokenAssociations":"2","aliasKey":null,"ledgerId":"testnet","ethereumNonce":"0","stakingInfo":{"declineStakingReward":false,"stakePeriodStart":null,"pendingReward":"0 tℏ","stakedToMe":"0 tℏ","stakedAccountId":null,"stakedNodeId":null}}

**Comment by valeraOlexienko** [comment] 2024-05-17 07:38
Yes, I can confirm that with the latest version of the wallet, all should be fine, we tested it recently on our side too.
@marelh02 please let us know if you still have issues

**Comment by hgraphql** [comment] 2024-05-17 16:56
@valeraOlexienko @marelh02 

I'm going to close this issue as resolved. @marelh02 if you still have issues please ping and we can re-open

**Closed by hgraphql** 2024-05-17 16:56 UTC
